/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProposalContract } from "./ProposalContract";
export * as factories from "./factories";
export { ProposalContract__factory } from "./factories/ProposalContract__factory";
